name: Java CI
on: [push]
jobs:
  jenkins-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Set up Jenkins
        uses: jenkinsci/jfr-setup-action@master
        with:
          jenkinsVersion: '2.401.3'
      - name: Run Jenkins pipeline
        uses: jenkinsci/jfr-runtime-action@master
        with:
          command: run
          jenkinsfile: Jenkinsfile
